version: '3.8'
services:
  nuxt:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./app/:/src
      - /src/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
  ngrok:
    image: ngrok/ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http --domain=boatapp.ngrok.dev nuxt:3000
    ports:
      - "4040:4040"
