version: '3.8'
services:
  nuxt:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./app/:/src
      - /src/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
