version: '3.8'
services:
  nuxt:
    build:
      context: .
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    volumes:
      - ./app/:/src
      - /src/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NUXI_DISABLE_VITE_HMR: true
    command: npm run dev
    container_name: nuxt_app

  ngrok:
    image: ngrok/ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http --domain=${NGROK_DOMAIN} nuxt:3000
    ports:
      - "4040:4040"